apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: login-deployment
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: login
    spec:
      containers:
      - name: login-container
        # Run this image
        image: login-2509
        ports:
        - containerPort: 80
